query getProject($slug: String, $locales: [Locale!]!) {
  project(stage: PUBLISHED, locales: $locales, where: { slug: $slug }) {
    title
    description
    coverImage {
      url(
        transformation: {
          image: { resize: { height: 1000 } }
          document: { output: { format: webp } }
        }
      )
    }
    projectInformation {
      client
      projectLocation
      startDate
      endDate
      siteArea
      floorArea
      services
    }
    projectGallery {
      image {
        url(
          transformation: {
            document: { output: { format: webp } }
            image: { resize: { height: 1000 } }
          }
        )
      }
    }
  }
}
