query getPeople($locales: [Locale!]!) {
  people(stage: PUBLISHED, locales: $locales) {
    name
    role
    photo {
      url(
        transformation: {
          document: { output: { format: webp } }
          image: { resize: { height: 200 } }
        }
      )
    }
  }
}
